test:
  # assemblies to test - optional
  assemblies:
    - \SampleWebAPI\SampleWebAPITests\bin\Debug\SampleWebAPITests.dll
  categories:
    - A
    - B
artifacts:
  - path: \SampleWebAPI
    name: SampleWebAPI
deploy:
  - provider: WebDeploy
    server: https://samplewebapi25.scm.azurewebsites.net/msdeploy.axd?site=samplewebapi25
    website: samplewebapi25
    username: samplewebapi25
    password: $(password)
    remove_files: true
    app_offline: true
    artifact: SampleWebAPI